name: co_quant_mri
channels:
  - simpleitk
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - autopep8=2.0.1
  - cudatoolkit=11.6.0
  - h5py=3.7.0
  - imageio=2.6.1
  - ipykernel=6.15.1
  - ipython=8.4.0
  - jupyter=1.0.0
  - matplotlib=3.2.2
  - numpy=1.23.1
  - pandas=1.5.2
  - pillow=7.2.0
  - pydicom=2.3.1
  - python=3.8.0
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - scikit-image=0.19.3
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - setuptools=59.5.0
  - statsmodels=0.13.5
  - simpleitk=2.1.1.1
  - tensorboard=2.9.1
  - yaml=0.2.5

