name: co_quant_mri
channels:
  - simpleitk
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.2.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - aom=3.4.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - autopep8=2.0.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.115
  - blas-devel=3.9.0
  - blinker=1.4
  - blosc=1.21.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.2.0
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - certifi=2022.12.7
  - cffi=1.14.4
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=2.1.0
  - click=8.1.3
  - cloudpickle=2.1.0
  - cryptography=37.0.4
  - cudatoolkit=11.6.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.1
  - dav1d=1.0.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - enum34=1.1.10
  - executing=0.9.1
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - giflib=5.2.1
  - google-auth=2.9.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.46.3
  - h5py<3.2
  - hdf5=1.12.1
  - icu=67.1
  - idna=3.3
  - imagecodecs-lite=2019.12.3
  - imageio=2.6.1
  - importlib-metadata=4.11.4
  - iniconfig=1.1.1
  - ipykernel=6.15.1
  - ipython=8.4.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=4.11.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.47.0
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - llvm-openmp=14.0.4
  - locket=1.0.0
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - matplotlib-inline=0.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - multidict=6.0.2
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.5
  - numpy=1.23.1
  - oauthlib=3.2.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=21.3
  - pandas=1.5.2
  - parso=0.8.3
  - partd=1.2.0
  - pathlib=1.0.1
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=22.2
  - pluggy=1.0.0
  - prompt-toolkit=3.0.30
  - protobuf=3.19.4
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydicom=2.3.1
  - pygments=2.12.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.8.0
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-image=0.19.3
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - setuptools=59.5.0
  - simpleitk=2.1.1.1
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.2
  - stack_data=0.3.0
  - statsmodels=0.13.5
  - tbb=2021.5.0
  - tensorboard=2.9.1
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=2.2.0
  - tifffile=2019.7.26.2
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.3.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - werkzeug=2.2.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
